# Generated by Django 4.1.5 on 2023-02-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('C', 'Complete'), ('D', 'Delete')], default='IP', max_length=60)),
                ('discription', models.TextField(blank=True, max_length=400, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
