# Generated by Django 4.1.5 on 2023-02-10 14:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='task_name'),
        ),
    ]
