# Generated by Django 4.1.5 on 2023-02-14 18:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0003_alter_task_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='media/uploads/profile_picture/default.jpg', upload_to='uploads/profile_picture')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='In Progress', max_length=60),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
