# Generated by Django 4.1.5 on 2023-02-18 17:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_task_options_alter_task_date_alter_task_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='task_name'),
        ),
    ]
